name: CI
on: [push]

jobs:
  sast_scan:
    name: Run Bandit SCan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: install python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -ll -ii -r . -f json -o bandit-report.json

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: bandit-findings
        path: bandit-report.json
  image_scan:
    name: Run image scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: set up docker
      uses: docker-practice/actions-setup-docker@v1
      with:
        docker_version: '20.10.7'
    - name: build docker file
      run:  docker build -f Dockerfile -t myapp:latest .

    - name: docker scout
      run:  |
            curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s --
            sh install-scot.sh
            docker scout quickview
            docker scout cves
      
      
    
        
  
